# Generated by 'nixos-generate-config'. Replace with actual hardware config.
{ modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # TODO: replace with actual disk UUIDs after installation
  # boot.initrd.luks.devices = { };
  # fileSystems."/" = { };
  # fileSystems."/boot" = { };
  # swapDevices = [ ];
}
